/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConversationsVerifyRouteImport } from './routes/conversations/verify'
import { Route as ConversationsMeRouteImport } from './routes/conversations/me'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin/messages'
import { Route as AuthenticatedAdminMessagesIndexRouteImport } from './routes/_authenticated/admin/messages/index'
import { Route as AuthenticatedAdminMessagesMessageIdRouteImport } from './routes/_authenticated/admin/messages/$messageId'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsVerifyRoute = ConversationsVerifyRouteImport.update({
  id: '/conversations/verify',
  path: '/conversations/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsMeRoute = ConversationsMeRouteImport.update({
  id: '/conversations/me',
  path: '/conversations/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/admin/messages',
    path: '/admin/messages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMessagesIndexRoute =
  AuthenticatedAdminMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminMessagesRoute,
  } as any)
const AuthenticatedAdminMessagesMessageIdRoute =
  AuthenticatedAdminMessagesMessageIdRouteImport.update({
    id: '/$messageId',
    path: '/$messageId',
    getParentRoute: () => AuthenticatedAdminMessagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/admin/login': typeof AdminLoginRoute
  '/conversations/me': typeof ConversationsMeRoute
  '/conversations/verify': typeof ConversationsVerifyRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/messages/$messageId': typeof AuthenticatedAdminMessagesMessageIdRoute
  '/admin/messages/': typeof AuthenticatedAdminMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/admin/login': typeof AdminLoginRoute
  '/conversations/me': typeof ConversationsMeRoute
  '/conversations/verify': typeof ConversationsVerifyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/messages/$messageId': typeof AuthenticatedAdminMessagesMessageIdRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/contact': typeof ContactRoute
  '/admin/login': typeof AdminLoginRoute
  '/conversations/me': typeof ConversationsMeRoute
  '/conversations/verify': typeof ConversationsVerifyRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/messages/$messageId': typeof AuthenticatedAdminMessagesMessageIdRoute
  '/_authenticated/admin/messages/': typeof AuthenticatedAdminMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/admin/login'
    | '/conversations/me'
    | '/conversations/verify'
    | '/admin/messages'
    | '/admin/'
    | '/admin/messages/$messageId'
    | '/admin/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/admin/login'
    | '/conversations/me'
    | '/conversations/verify'
    | '/admin'
    | '/admin/messages/$messageId'
    | '/admin/messages'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/admin/login'
    | '/conversations/me'
    | '/conversations/verify'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/messages/$messageId'
    | '/_authenticated/admin/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ContactRoute: typeof ContactRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ConversationsMeRoute: typeof ConversationsMeRoute
  ConversationsVerifyRoute: typeof ConversationsVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/verify': {
      id: '/conversations/verify'
      path: '/conversations/verify'
      fullPath: '/conversations/verify'
      preLoaderRoute: typeof ConversationsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/me': {
      id: '/conversations/me'
      path: '/conversations/me'
      fullPath: '/conversations/me'
      preLoaderRoute: typeof ConversationsMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/messages/': {
      id: '/_authenticated/admin/messages/'
      path: '/'
      fullPath: '/admin/messages/'
      preLoaderRoute: typeof AuthenticatedAdminMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminMessagesRoute
    }
    '/_authenticated/admin/messages/$messageId': {
      id: '/_authenticated/admin/messages/$messageId'
      path: '/$messageId'
      fullPath: '/admin/messages/$messageId'
      preLoaderRoute: typeof AuthenticatedAdminMessagesMessageIdRouteImport
      parentRoute: typeof AuthenticatedAdminMessagesRoute
    }
  }
}

interface AuthenticatedAdminMessagesRouteChildren {
  AuthenticatedAdminMessagesMessageIdRoute: typeof AuthenticatedAdminMessagesMessageIdRoute
  AuthenticatedAdminMessagesIndexRoute: typeof AuthenticatedAdminMessagesIndexRoute
}

const AuthenticatedAdminMessagesRouteChildren: AuthenticatedAdminMessagesRouteChildren =
  {
    AuthenticatedAdminMessagesMessageIdRoute:
      AuthenticatedAdminMessagesMessageIdRoute,
    AuthenticatedAdminMessagesIndexRoute: AuthenticatedAdminMessagesIndexRoute,
  }

const AuthenticatedAdminMessagesRouteWithChildren =
  AuthenticatedAdminMessagesRoute._addFileChildren(
    AuthenticatedAdminMessagesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ContactRoute: ContactRoute,
  AdminLoginRoute: AdminLoginRoute,
  ConversationsMeRoute: ConversationsMeRoute,
  ConversationsVerifyRoute: ConversationsVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
