/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AuthenticatedAdminMessagesIndexRouteImport } from './routes/_authenticated/admin/messages/index'
import { Route as AuthenticatedAdminMessagesMessageIdRouteImport } from './routes/_authenticated/admin/messages/$messageId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminMessagesIndexRoute =
  AuthenticatedAdminMessagesIndexRouteImport.update({
    id: '/admin/messages/',
    path: '/admin/messages/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMessagesMessageIdRoute =
  AuthenticatedAdminMessagesMessageIdRouteImport.update({
    id: '/admin/messages/$messageId',
    path: '/admin/messages/$messageId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages/$messageId': typeof AuthenticatedAdminMessagesMessageIdRoute
  '/admin/messages/': typeof AuthenticatedAdminMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages/$messageId': typeof AuthenticatedAdminMessagesMessageIdRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/_authenticated/admin/messages/$messageId': typeof AuthenticatedAdminMessagesMessageIdRoute
  '/_authenticated/admin/messages/': typeof AuthenticatedAdminMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/login'
    | '/admin/messages/$messageId'
    | '/admin/messages/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/login' | '/admin/messages/$messageId' | '/admin/messages'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin/login'
    | '/_authenticated/admin/messages/$messageId'
    | '/_authenticated/admin/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/messages/': {
      id: '/_authenticated/admin/messages/'
      path: '/admin/messages'
      fullPath: '/admin/messages/'
      preLoaderRoute: typeof AuthenticatedAdminMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/messages/$messageId': {
      id: '/_authenticated/admin/messages/$messageId'
      path: '/admin/messages/$messageId'
      fullPath: '/admin/messages/$messageId'
      preLoaderRoute: typeof AuthenticatedAdminMessagesMessageIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminMessagesMessageIdRoute: typeof AuthenticatedAdminMessagesMessageIdRoute
  AuthenticatedAdminMessagesIndexRoute: typeof AuthenticatedAdminMessagesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminMessagesMessageIdRoute:
    AuthenticatedAdminMessagesMessageIdRoute,
  AuthenticatedAdminMessagesIndexRoute: AuthenticatedAdminMessagesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
